version: "3"

networks:
  app-net:
    driver: bridge

services:
  martini-be:
    build:
      context: ./martini-be
    environment:
      # GIN_MODE: release
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASS}
      PG_DBNAME: ${PG_DB}
      PG_PORT: ${PG_DB_PORT}
    networks:
      - app-net
    ports:
      - "8010:8010"
    depends_on:
      - martini-db

  martini-db:
    image: postgres:latest
    ports:
      - "${PG_DB_PORT}:${PG_DB_PORT}"
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      PGPORT: ${PG_DB_PORT}
    networks:
      - app-net
    volumes:
      - postgres-app-data:/var/lib/postgresql/data

volumes:
  postgres-app-data:
